# Configuration for @name@
#
# Version: @version@

Custom-Permissions:
  Core-Command: 'bstaff.core'
  Toggle-Staff-Messages: 'bstaff.togglestaffmessages'
  StaffChat-Command: 'bstaff.staffchat'
  Staff-Follow: 'bstaff.follow'
  Staff-List: 'bstaff.stafflist'
  Broadcast-Command: 'bstaff.broadcast'

Use-Tab-Completion: true

Cooldowns:
  Request: 60
  Report: 60

Defaults:
  Staff-Messages: true

# Prefix to use, when there's none defined for the player.
# ( this is only used if you delete the default rank against my notes ;) )
No-Rank: '&7'

# Auto save settings
auto-save:
  enabled: true
  # Interval in seconds
  interval: 60

storage:
  # Staff users won't be synced properly when yml is used.
  # yml/mysql
  type: mysql
  mysql:
    host: localhost
    port: 3306
    user: root
    pass: secretpassword
    database: bungeestaff
    tables:
      users: 'staff'
  yml:
    file: 'users'

# RabbitMQ configuration for multi-proxy messaging.
# Note: Messages received over Rabbit use the origin message format.
Rabbit:
  Enabled: true
  Host: 'localhost'
  Port: 5672
  Username: 'root'
  Password: 'pass'
  User-Update-Interval: 10