# Configuration for @name@
#
# Version: @version@

Custom-Permissions:
  Core-Command: 'bstaff.core'
  Toggle-Staff-Messages: 'bstaff.togglestaffmessages'
  Staff-Join: 'bstaff.staff.join'
  Staff-Leave: 'bstaff.staff.leave'
  StaffChat-Command: 'bstaff.staffchat'
  Request-Notify: 'bstaff.request.notify'
  Report-Notify: 'bstaff.report.notify'
  Staff-Follow: 'bstaff.follow'
  Staff-List: 'bstaff.stafflist'
  Broadcast-Command: 'bstaff.broadcast'
  Server-Switch: 'bstaff.serverswitch'
  Server-Switch-Notify: 'bstaff.serverswitch.notify'

Use-Tab-Completion: true

Cooldowns:
  Request: 60
  Report: 60

Defaults:
  Staff-Messages: true

# Prefix to use, when there's none defined for the player.
# ( this is only used if you delete the default rank against my notes ;) )
No-Rank: '&7'

# RabbitMQ configuration for multi-proxy messaging.
# Note: Messages received over Rabbit use the origin message format.
Rabbit:
  Enabled: true
  Host: 'localhost'
  Port: 5672
  Username: 'root'
  Password: 'pass'